# build.ps1 – Defender
# Combines all modules into defender_final.ps1
# Run on Windows VM only

$output = "$PSScriptRoot\defender_final.ps1"
$modulesPath = "$PSScriptRoot\modules"

# Header
@"
# defender_final.ps1
# Auto-generated by build.ps1 – do not edit manually
# Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@ | Set-Content $output

# Collect and combine all modules recursively
$modules = Get-ChildItem -Path $modulesPath -Recurse -Filter "*.ps1"

if ($modules.Count -eq 0) {
    Write-Host "[-] No modules found in $modulesPath" -ForegroundColor Red
    exit 1
}

foreach ($module in $modules) {
    "" | Add-Content $output
    "# === $($module.FullName) ===" | Add-Content $output
    Get-Content $module.FullName | Add-Content $output
    Write-Host "[+] Added: $($module.Name)" -ForegroundColor Green
}

Write-Host ""
Write-Host "[+] Build complete: $output" -ForegroundColor Cyan
Write-Host "[+] Modules included: $($modules.Count)" -ForegroundColor Cyan